name: barberapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  shared_preferences: ^2.5.3
  random_string: ^2.3.1
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_stripe: ^12.0.2
  url_launcher: ^6.3.2
  bkash: ^0.0.2
  image_picker: ^1.2.0
  flutter_sslcommerz: ^2.5.1
  uddoktapay: ^0.0.6
  get: ^4.7.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

# Configuration for flutter_launcher_icons (top-level)
flutter_icons:
  android: true
  ios: true
  image_path: images/Shop-Logo.png
  adaptive_icon_background: '#FFFFFF'
  remove_alpha_ios: true
