// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQvOAwJjvYnGYO2B1YLUjfvT9HKhbTeA',
    appId: '1:258916185007:web:45aca87ef1200676e3b55a',
    messagingSenderId: '258916185007',
    projectId: 'trimease-1a9be',
    authDomain: 'trimease-1a9be.firebaseapp.com',
    storageBucket: 'trimease-1a9be.firebasestorage.app',
    measurementId: 'G-G9Z89N30WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVNNqseJTvCOlR8riLPIC9Kj1rmp49vT0',
    appId: '1:258916185007:android:74dc370850e01fd6e3b55a',
    messagingSenderId: '258916185007',
    projectId: 'trimease-1a9be',
    storageBucket: 'trimease-1a9be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWVllOfA7nO2gaIQkEX2hXVhH3tWKxac',
    appId: '1:258916185007:ios:3d59346a17ab670de3b55a',
    messagingSenderId: '258916185007',
    projectId: 'trimease-1a9be',
    storageBucket: 'trimease-1a9be.firebasestorage.app',
    iosBundleId: 'com.example.barberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWVllOfA7nO2gaIQkEX2hXVhH3tWKxac',
    appId: '1:258916185007:ios:3d59346a17ab670de3b55a',
    messagingSenderId: '258916185007',
    projectId: 'trimease-1a9be',
    storageBucket: 'trimease-1a9be.firebasestorage.app',
    iosBundleId: 'com.example.barberapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQvOAwJjvYnGYO2B1YLUjfvT9HKhbTeA',
    appId: '1:258916185007:web:1ea9b2f23f64797ce3b55a',
    messagingSenderId: '258916185007',
    projectId: 'trimease-1a9be',
    authDomain: 'trimease-1a9be.firebaseapp.com',
    storageBucket: 'trimease-1a9be.firebasestorage.app',
    measurementId: 'G-7BCDLCMYWH',
  );
}
